language: node_js
node_js:
  - '12'

install:
  - yarn cache clean
  - yarn

script:
  - yarn build
  - yarn test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
